; ------------------------------------------------------------------------------

ObjectIndex:
	dc.l	PlayerObject
	dc.l	PlayerObject
	dc.l	PowerupObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	TestObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	InvisibleBlockObject
	dc.l	SpringObject
	dc.l	HDoorSplashObject
	dc.l	HDoorSplashSetObject
	dc.l	HDoorObject
	dc.l	TunnelSplashObject
	dc.l	MoveSpringObjectR8
	dc.l	RingObject
	dc.l	LostRingObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	BigRingObject
	dc.l	CapsuleObject
	dc.l	GoalObject
	dc.l	SignpostObject
	dc.l	ExplosionObject
	dc.l	MonitorTimeObject
	dc.l	MonitorItemObject
	dc.l	BoulderObject
	dc.l	HudPointsObject
	dc.l	BumperObject
	dc.l	NullObject
	dc.l	FlowerObject
	dc.l	NullObject
	dc.l	SwitchObject
	dc.l	SpinDiscObject
	dc.l	NullObject
	dc.l	MechaBuObject
	dc.l	CollapseFloorObject
	dc.l	NullObject
	dc.l	BuzzsawObject
	dc.l	NullObject
	dc.l	DoorObject
	dc.l	SpinPlatformObject
	dc.l	SpikeWallObject
	dc.l	VanishPlatformObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	AnimalObject
	dc.l	SpikeCrusherObject
	dc.l	CrusherObject
	dc.l	NullObject
	dc.l	SpikesObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	HotaruObject
	dc.l	ResultsObject
	dc.l	GameOverObject
	dc.l	TitleCardObject
	dc.l	BossDoorObject
	dc.l	RevolveDoorObject
	dc.l	EggmanObject
	dc.l	BossPanelObject
	dc.l	EggMobileObject
	dc.l	SparksObject
	dc.l	AmyRoseObject

; ------------------------------------------------------------------------------
