; ------------------------------------------------------------------------------

ObjectIndex:
	dc.l	PlayerObject
	dc.l	PlayerObject
	dc.l	PowerupObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	TestObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	SpringObject
	dc.l	HDoorSplashObject
	dc.l	HDoorSplashSetObject
	dc.l	HDoorObject
	dc.l	TunnelSplashObject
	dc.l	MobileSpringObjectR8
	dc.l	RingObject
	dc.l	LostRingObject
	dc.l	NullObject
	dc.l	CheckpointObject
	dc.l	BigRingObject
	dc.l	CapsuleObject
	dc.l	GoalObject
	dc.l	SignpostObject
	dc.l	ExplosionObject
	dc.l	MonitorTimeObject
	dc.l	MonitorItemObject
	dc.l	BoulderObject
	dc.l	HudPointsObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	FlowerObject
	dc.l	NullObject
	dc.l	SwitchObject
	dc.l	SpinDiscObject
	dc.l	NullObject
	dc.l	MechaBuObject
	dc.l	CollapseFloorObject
	dc.l	NullObject
	dc.l	BuzzsawObject
	dc.l	PropellerObject
	dc.l	DoorObject
	dc.l	SpinPlatformObject
	dc.l	NullObject
	dc.l	VanishPlatformObject
	dc.l	NullObject
	dc.l	PohBeeObject
	dc.l	ScarabObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	AnimalObject
	dc.l	NullObject
	dc.l	CrusherObject
	dc.l	SeesawObject
	dc.l	SpikesObject
	dc.l	TrapDoorObject
	dc.l	HVPlatformObject
	dc.l	NullObject
	dc.l	ResultsObject
	dc.l	GameOverObject
	dc.l	TitleCardObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	RobotGeneratorObject
	
; ------------------------------------------------------------------------------