; ------------------------------------------------------------------------------

ObjectIndex:
	dc.l	PlayerObject
	dc.l	PlayerObject
	dc.l	PowerupObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	TestObject
	dc.l	TunnelPathObject
	dc.l	NullObject
	dc.l	InvisibleBlockObject
	dc.l	SpringObject
	dc.l	HDoorSplashObject
	dc.l	HDoorSplashSetObject
	dc.l	HDoorObject
	dc.l	TunnelSplashObject
	dc.l	MobileSpringObjectR8
	dc.l	RingObject
	dc.l	LostRingObject
	dc.l	NullObject
	dc.l	CheckpointObject
	dc.l	BigRingObject
	dc.l	CapsuleObject
	dc.l	GoalObject
	dc.l	SignpostObject
	dc.l	ExplosionObject
	dc.l	MonitorTimeObject
	dc.l	MonitorItemObject
	dc.l	BoulderObject
	dc.l	HudPointsObject
	dc.l	LaserObject
	dc.l	NullObject
	dc.l	FlowerObject
	dc.l	TubeDoorObject
	dc.l	SwitchObject
	dc.l	SpinDiscObject
	dc.l	BigbomObject
	dc.l	MechaBuObject
	dc.l	CollapseFloorObject
	dc.l	TwinWalkerObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	DoorObject
	dc.l	NullObject
	dc.l	SpikeWallObject
	dc.l	VanishPlatformObject
	dc.l	DangoObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	TrapDoorObject
	dc.l	NullObject
	dc.l	AnimalObject
	dc.l	SpikeCrusherObject
	dc.l	CrusherObject
	dc.l	SeesawObject
	dc.l	SpikesObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	ResultsObject
	dc.l	GameOverObject
	dc.l	TitleCardObject
	dc.l	BossDoorObject
	dc.l	RevolveDoorObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	RobotGeneratorObject
	
; ------------------------------------------------------------------------------