@echo off
set REGION=1

if %REGION%==0 (set REGPATH=Japan)
if %REGION%==1 (set REGPATH=USA)
if %REGION%==2 (set REGPATH=Europe)

if %REGION%==0 fc /b original\ip_japan.bin out\misc\ip.bin
if %REGION%==1 fc /b original\ip_usa.bin out\misc\ip.bin
if %REGION%==2 fc /b original\ip_europe.bin out\misc\ip.bin
fc /b original\sp.bin out\misc\sp.bin
fc /b original\%REGPATH%\IPX___.MMD out\files\IPX___.MMD
fc /b original\%REGPATH%\SPX___.BIN out\files\SPX___.BIN
fc /b original\%REGPATH%\BRAMINIT.MMD out\files\BRAMINIT.MMD
fc /b original\%REGPATH%\BRAMSUB.BIN out\files\BRAMSUB.BIN
fc /b original\%REGPATH%\MDINIT.MMD out\files\MDINIT.MMD
fc /b original\%REGPATH%\WARP__.MMD out\files\WARP__.MMD
fc /b original\%REGPATH%\SNCBNK1B.BIN out\files\SNCBNK1B.BIN
fc /b original\%REGPATH%\SNCBNK3B.BIN out\files\SNCBNK3B.BIN
fc /b original\%REGPATH%\SNCBNK4B.BIN out\files\SNCBNK4B.BIN
fc /b original\%REGPATH%\SNCBNK5B.BIN out\files\SNCBNK5B.BIN
fc /b original\%REGPATH%\SNCBNK6B.BIN out\files\SNCBNK6B.BIN
fc /b original\%REGPATH%\SNCBNK7B.BIN out\files\SNCBNK7B.BIN
fc /b original\%REGPATH%\SNCBNK8B.BIN out\files\SNCBNK8B.BIN
fc /b original\%REGPATH%\SNCBNKB1.BIN out\files\SNCBNKB1.BIN
fc /b original\%REGPATH%\SNCBNKB2.BIN out\files\SNCBNKB2.BIN
fc /b original\%REGPATH%\TITLEM.MMD out\files\TITLEM.MMD
fc /b original\%REGPATH%\TITLES.BIN out\files\TITLES.BIN
fc /b original\%REGPATH%\STSEL_.MMD out\files\STSEL_.MMD
fc /b original\%REGPATH%\SOSEL_.MMD out\files\SOSEL_.MMD
fc /b original\%REGPATH%\NISI.MMD out\files\NISI.MMD
fc /b original\%REGPATH%\DUMMY0.MMD out\files\DUMMY0.MMD
fc /b original\%REGPATH%\DUMMY1.MMD out\files\DUMMY1.MMD
fc /b original\%REGPATH%\DUMMY2.MMD out\files\DUMMY2.MMD
fc /b original\%REGPATH%\DUMMY3.MMD out\files\DUMMY3.MMD
fc /b original\%REGPATH%\DUMMY4.MMD out\files\DUMMY4.MMD
fc /b original\%REGPATH%\DUMMY5.MMD out\files\DUMMY5.MMD
fc /b original\%REGPATH%\DUMMY6.MMD out\files\DUMMY6.MMD
fc /b original\%REGPATH%\DUMMY7.MMD out\files\DUMMY7.MMD
fc /b original\%REGPATH%\DUMMY8.MMD out\files\DUMMY8.MMD
fc /b original\%REGPATH%\DUMMY9.MMD out\files\DUMMY9.MMD
fc /b original\%REGPATH%\SPEEND.MMD out\files\SPEEND.MMD
fc /b original\%REGPATH%\ATTACK.BIN out\files\ATTACK.BIN
fc /b original\%REGPATH%\THANKS_S.BIN out\files\THANKS_S.BIN
fc /b original\%REGPATH%\OPEN_M.MMD out\files\OPEN_M.MMD
fc /b original\%REGPATH%\OPEN_S.BIN out\files\OPEN_S.BIN
fc /b original\%REGPATH%\OPN.STM out\files\OPN.STM
fc /b original\%REGPATH%\GOODEND.BIN out\files\GOODEND.BIN
fc /b original\%REGPATH%\BADEND.BIN out\files\BADEND.BIN
fc /b original\%REGPATH%\PTEST.BIN out\files\PTEST.BIN
fc /b original\%REGPATH%\PLANET_M.MMD out\files\PLANET_M.MMD
fc /b original\%REGPATH%\PLANET_S.BIN out\files\PLANET_S.BIN
fc /b original\%REGPATH%\PLANET_D.BIN out\files\PLANET_D.BIN
fc /b original\%REGPATH%\VM____.MMD out\files\VM____.MMD
fc /b original\%REGPATH%\R11A__.MMD out\files\R11A__.MMD
fc /b original\%REGPATH%\R12A__.MMD out\files\R12A__.MMD
fc /b original\%REGPATH%\R12B__.MMD out\files\R12B__.MMD
fc /b original\%REGPATH%\R12C__.MMD out\files\R12C__.MMD
fc /b original\%REGPATH%\R12D__.MMD out\files\R12D__.MMD
fc /b original\%REGPATH%\R13C__.MMD out\files\R13C__.MMD
fc /b original\%REGPATH%\R13D__.MMD out\files\R13D__.MMD
fc /b original\%REGPATH%\DEMO11A.MMD out\files\DEMO11A.MMD
fc /b original\%REGPATH%\R11B__.MMD out\files\R11B__.MMD
fc /b original\%REGPATH%\R11C__.MMD out\files\R11C__.MMD
fc /b original\%REGPATH%\R11D__.MMD out\files\R11D__.MMD
fc /b original\%REGPATH%\R61A__.MMD out\files\R61A__.MMD
fc /b original\%REGPATH%\R61B__.MMD out\files\R61B__.MMD
fc /b original\%REGPATH%\R61C__.MMD out\files\R61C__.MMD
fc /b original\%REGPATH%\R61D__.MMD out\files\R61D__.MMD
fc /b original\%REGPATH%\R62A__.MMD out\files\R62A__.MMD
fc /b original\%REGPATH%\R62B__.MMD out\files\R62B__.MMD
fc /b original\%REGPATH%\R62C__.MMD out\files\R62C__.MMD
fc /b original\%REGPATH%\R62D__.MMD out\files\R62D__.MMD
fc /b original\%REGPATH%\R63C__.MMD out\files\R63C__.MMD
fc /b original\%REGPATH%\R63D__.MMD out\files\R63D__.MMD
fc /b original\%REGPATH%\R31A__.MMD out\files\R31A__.MMD
fc /b original\%REGPATH%\R31B__.MMD out\files\R31B__.MMD
fc /b original\%REGPATH%\R31C__.MMD out\files\R31C__.MMD
fc /b original\%REGPATH%\R31D__.MMD out\files\R31D__.MMD
fc /b original\%REGPATH%\R32A__.MMD out\files\R32A__.MMD
fc /b original\%REGPATH%\R32B__.MMD out\files\R32B__.MMD
fc /b original\%REGPATH%\R32C__.MMD out\files\R32C__.MMD
fc /b original\%REGPATH%\R32D__.MMD out\files\R32D__.MMD
fc /b original\%REGPATH%\R33C__.MMD out\files\R33C__.MMD
fc /b original\%REGPATH%\R33D__.MMD out\files\R33D__.MMD
fc /b original\%REGPATH%\R41A__.MMD out\files\R41A__.MMD
fc /b original\%REGPATH%\R41B__.MMD out\files\R41B__.MMD
fc /b original\%REGPATH%\R41C__.MMD out\files\R41C__.MMD
fc /b original\%REGPATH%\R41D__.MMD out\files\R41D__.MMD
fc /b original\%REGPATH%\R42A__.MMD out\files\R42A__.MMD
fc /b original\%REGPATH%\R42B__.MMD out\files\R42B__.MMD
fc /b original\%REGPATH%\R42C__.MMD out\files\R42C__.MMD
fc /b original\%REGPATH%\R42D__.MMD out\files\R42D__.MMD
fc /b original\%REGPATH%\R43C__.MMD out\files\R43C__.MMD
fc /b original\%REGPATH%\R43D__.MMD out\files\R43D__.MMD
fc /b original\%REGPATH%\DEMO43C.MMD out\files\DEMO43C.MMD
fc /b original\%REGPATH%\R51A__.MMD out\files\R51A__.MMD
fc /b original\%REGPATH%\R51B__.MMD out\files\R51B__.MMD
fc /b original\%REGPATH%\R51C__.MMD out\files\R51C__.MMD
fc /b original\%REGPATH%\R51D__.MMD out\files\R51D__.MMD
fc /b original\%REGPATH%\R52A__.MMD out\files\R52A__.MMD
fc /b original\%REGPATH%\R52B__.MMD out\files\R52B__.MMD
fc /b original\%REGPATH%\R52C__.MMD out\files\R52C__.MMD
fc /b original\%REGPATH%\R52D__.MMD out\files\R52D__.MMD
fc /b original\%REGPATH%\R53C__.MMD out\files\R53C__.MMD
fc /b original\%REGPATH%\R53D__.MMD out\files\R53D__.MMD
fc /b original\%REGPATH%\R71A__.MMD out\files\R71A__.MMD
fc /b original\%REGPATH%\R71B__.MMD out\files\R71B__.MMD
fc /b original\%REGPATH%\R71C__.MMD out\files\R71C__.MMD
fc /b original\%REGPATH%\R71D__.MMD out\files\R71D__.MMD
fc /b original\%REGPATH%\R72A__.MMD out\files\R72A__.MMD
fc /b original\%REGPATH%\R72B__.MMD out\files\R72B__.MMD
fc /b original\%REGPATH%\R72C__.MMD out\files\R72C__.MMD
fc /b original\%REGPATH%\R72D__.MMD out\files\R72D__.MMD
fc /b original\%REGPATH%\R73C__.MMD out\files\R73C__.MMD
fc /b original\%REGPATH%\R73D__.MMD out\files\R73D__.MMD
fc /b original\%REGPATH%\R81A__.MMD out\files\R81A__.MMD
fc /b original\%REGPATH%\R81B__.MMD out\files\R81B__.MMD
fc /b original\%REGPATH%\R81C__.MMD out\files\R81C__.MMD
fc /b original\%REGPATH%\R81D__.MMD out\files\R81D__.MMD
fc /b original\%REGPATH%\R82A__.MMD out\files\R82A__.MMD
fc /b original\%REGPATH%\DEMO82A.MMD out\files\DEMO82A.MMD
fc /b original\%REGPATH%\R82B__.MMD out\files\R82B__.MMD
fc /b original\%REGPATH%\R82C__.MMD out\files\R82C__.MMD
fc /b original\%REGPATH%\R82D__.MMD out\files\R82D__.MMD
fc /b original\%REGPATH%\R83C__.MMD out\files\R83C__.MMD
fc /b original\%REGPATH%\R83D__.MMD out\files\R83D__.MMD
fc /b original\%REGPATH%\SPMM__.MMD out\files\SPMM__.MMD
fc /b original\%REGPATH%\SPSS__.BIN out\files\SPSS__.BIN

pause
