; -------------------------------------------------------------------------
; Sonic CD Disassembly
; Tidal Tempest Act 1 shared entry graph
; -------------------------------------------------------------------------

	include	"Level/Initialization.asm"
	include	"Level/Tidal Tempest/R4 Compatibility.asm"
	include	"Level/Tidal Tempest/Palette Cycle (Act 1 Variant).asm"
	include	"Level/Palette Fade.asm"
	include	"Level/Palette Load (Fade).asm"
	include	"Level/Palette Load.asm"
	include	"Level/Palette Load (Water).asm"
	include	"Level/Palette Load (Water Fade).asm"
	include	"Level/Tidal Tempest/Palette Data (Act 1 Variant).asm"
	include	"Level/Functions (Misc).asm"
	include	"Level/Collision Floor.asm"
	include	"Level/Main.asm"
	include	"Level/Functions (General).asm"
	include	"Level/Tidal Tempest/Stage Draw (Act 1 Variant).asm"
	include	"Level/Block Draw.asm"
	include	"Level/Tidal Tempest/Scroll (Act 1 Variant).asm"
	include	"Level/Palmtree Panic/Load Level Data.asm"
	include	"Level/Tidal Tempest/Events.asm"
	include	"Level/Object Functions.asm"
	include	"Level/Object Tile ID Set.asm"
	include	"Level/Collision Chaos/Object Tile IDs (Act 1 Present).asm"

	if TT_VARIANT=0
		include	"r4/object_index_1a.asm"
	else
		if TT_VARIANT=1
			include	"r4/object_index_1b.asm"
		else
			include	"r4/object_index_1c_1d.asm"
		endif
	endif

	include	"Level/_Objects/Sonic/Main.asm"
	include	"Level/Palmtree Panic/Player Special Collision.asm"
	include	"Level/Sub CPU.asm"
	include	"Level/Object Animate.asm"
	include	"Level/_Objects/Checkpoint/Main.asm"
	include	"Level/Resume Music (Leftover).asm"
	include	"Level/_Objects/Test Badnik/Main.asm"
	include	"Level/_Objects/Explosion/Main.asm"
	include	"Level/_Objects/Flower/Main.asm"
	include	"Level/_Objects/Spin Tunnel/Main (Waterfall Splash).asm"
	include	"Level/_Objects/Spin Tunnel/Main (Door).asm"
	include	"Level/_Objects/Powerup/Main.asm"
	include	"Level/Load Saved Data.asm"
	include	"Level/Collision Check.asm"
	include	"Level/Tidal Tempest/Player Object Collision.asm"
	include	"Level/Debug Mode.asm"
	include	"Level/Tidal Tempest/Debug Objects (Act 1 Variant).asm"
	include	"Level/Object Spawner.asm"
	include	"Level/Tidal Tempest/Object Layout (Act 1).asm"
	include	"Level/Object Solid.asm"

	include	"objects/r4/player_bubbles.asm"
	include	"objects/r4/test.asm"
	include	"objects/r4/splash.asm"
	include	"objects/r4/water_surface.asm"
	include	"objects/r4/break_pole.asm"

	include	"Level/_Objects/Boulder/Main.asm"
	include	"Level/_Objects/Spring/Main.asm"
	include	"Level/_Objects/Ring/Main.asm"
	include	"Level/_Objects/Monitor and Time Post/Main.asm"
	include	"Level/_Objects/HUD and Points/Main.asm"
	include	"objects/r4/bubble_spawner.asm"
	include	"Level/_Objects/Level End/Main.asm"
	include	"Level/_Objects/Game Over/Main.asm"
	include	"Level/_Objects/Title Card/Main.asm"
	include	"Level/_Objects/Results/Main.asm"
	include	"Level/Palmtree Panic/Title Card Data.asm"
	include	"Level/Object Time Check.asm"

	if TT_VARIANT=0
		include	"objects/r4/spikes.asm"
		include	"objects/r4/h_move_block.asm"
		include	"objects/r4/elevator.asm"
		include	"objects/r4/switch.asm"
		include	"objects/r4/door.asm"
		include	"objects/r4/swing.asm"
		include	"objects/r4/geyser.asm"
		include	"objects/r4/tonbo.asm"
		include	"objects/r4/amenbo.asm"
		include	"objects/r4/taga_taga.asm"
		include	"objects/r4/yago.asm"
		include	"objects/r4/animal.asm"
		include	"objects/r4/switch_elevator.asm"
		include	"objects/r4/fall_spikes.asm"
		include	"objects/r4/crush_blocks.asm"
		include	"objects/r4/block.asm"
		include	"objects/r4/fan_a_b.asm"
		include	"objects/r4/mace.asm"
		include	"objects/r4/collapse_floor.asm"
		include	"objects/r4/break_block.asm"
		include	"objects/r4/robot_generator.asm"
	elseif TT_VARIANT=1
		include	"objects/r4/spikes.asm"
		include	"objects/r4/v_move_block.asm"
		include	"objects/r4/h_move_block.asm"
		include	"objects/r4/switch.asm"
		include	"objects/r4/tonbo.asm"
		include	"objects/r4/amenbo.asm"
		include	"objects/r4/taga_taga.asm"
		include	"objects/r4/yago.asm"
		include	"objects/r4/animal.asm"
		include	"objects/r4/crush_blocks.asm"
		include	"objects/r4/block.asm"
		include	"objects/r4/fan_a_b.asm"
		include	"objects/r4/rotate_block.asm"
		include	"objects/r4/robot_generator.asm"
		include	"objects/r4/projector.asm"
	else
		include	"objects/r4/spikes.asm"
		include	"objects/r4/v_move_block.asm"
		include	"objects/r4/h_move_block.asm"
		include	"objects/r4/switch.asm"
		include	"objects/r4/tonbo.asm"
		include	"objects/r4/amenbo.asm"
		include	"objects/r4/taga_taga.asm"
		include	"objects/r4/yago.asm"
		include	"objects/r4/animal.asm"
		include	"objects/r4/block.asm"
		include	"objects/r4/fan_c_d.asm"
		include	"objects/r4/circle_spike_ball.asm"
		include	"objects/r4/platform_chain.asm"
		include	"objects/r4/prize.asm"
		include	"objects/r4/elevator.asm"
	endif

	include	"Level/Tidal Tempest/Animated Tiles Update (Act 1 Variant).asm"
	include	"Level/Section Art Load.asm"
	include	"Level/Tidal Tempest/Section Data (Act 1 Variant).asm"
	include	"Level/Tidal Tempest/R4 Object Data.asm"
	include	"Level/Tidal Tempest/Data (Act 1 Variant).asm"
