; -------------------------------------------------------------------------
; Tidal Tempest R41B historical source graph
; -------------------------------------------------------------------------

STANDALONE		EQU	0
R6_LEGACY_PLAYER	EQU	1

	include	"Level/Initialization.asm"
	include	"Level/Tidal Tempest/R4 Legacy Compatibility.asm"

	include "r4/palette_cycle_b.asm"
	include "common/palette_fade.asm"
	include "common/palette_load_fade.asm"
	include "common/palette_load.asm"
	include "common/palette_load_water.asm"
	include "common/palette_load_water_fade.asm"
	include "r4/palettes_b.asm"
	include "common/s1_object_despawn.asm"
	include "common/vsync.asm"
	include "common/math.asm"
	include "common/player_ground_collide.asm"
	include "common/block_collide.asm"
	include "r4/main.asm"
	include "common/random.asm"
	include "common/joypad.asm"
	include "common/vdp.asm"
	include "common/z80.asm"
	include "common/sound.asm"
	include "common/tilemap.asm"
	include "common/nemesis.asm"
	include "common/gfx_queue.asm"
	include "common/enigma.asm"
	include "common/kosinski.asm"
	include "Level/Tidal Tempest/R41B Legacy Scroll.asm"
	include "r4/stage_draw_1b.asm"
	if STANDALONE<>0
		include	"standalone/block_write.asm"
	endif
	include "r4/stage_data_load_1b.asm"
	include "common/events.asm"
	include "common/object.asm"
	include "r4/object_index_1b.asm"
	include "objects/null.asm"
	include "objects/player.asm"
	include "common/sub_cpu.asm"
	include "common/object_animate.asm"
	include "objects/checkpoint.asm"
	include "objects/r4/player_bubbles.asm"
	include "objects/r4/test.asm"
	include "objects/explosion.asm"
	include "objects/flower.asm"
	include "objects/r4/splash.asm"
	include "objects/powerup.asm"
	include "objects/r4/water_surface.asm"
	include "objects/r4/break_pole.asm"
	include "common/player_block_check.asm"
	include "common/respawn_load.asm"
	include "common/object_block_collide.asm"
	include "r4/player_object_collide.asm"
	include "common/debug_mode.asm"
	include "r4/debug_objects_1b.asm"
	include "common/object_spawn.asm"
	include "r4/stage_object_maps_1.asm"
	include "common/solid_object.asm"
	include "objects/r1/boulder.asm"
	include "objects/spring.asm"
	include "objects/ring.asm"
	include "objects/monitor_time.asm"
	include "objects/hud_points.asm"
	include "objects/r4/bubble_spawner.asm"
	include "objects/stage_end.asm"
	include "objects/game_over.asm"
	include "objects/title_card.asm"
	include "objects/results.asm"
	include "r4/title_card_data.asm"
	include "r4/water_currents_1b.asm"
	include "r4/section_gfx_1b.asm"
	include "objects/r4/spikes.asm"
	include "objects/r4/v_move_block.asm"
	include "objects/r4/h_move_block.asm"
	include "objects/r4/switch.asm"
	include "objects/r4/tonbo.asm"
	include "objects/r4/amenbo.asm"
	include "objects/r4/taga_taga.asm"
	include "objects/r4/yago.asm"
	include "objects/r4/animal.asm"
	include "objects/r4/crush_blocks.asm"
	include "objects/r4/block.asm"
	include "objects/r4/fan_a_b.asm"
	include "objects/r4/rotate_block.asm"
	include "objects/r4/robot_generator.asm"
	include "objects/r4/projector.asm"
	include "common/time_check.asm"
	include "r4/stage_gfx_animate_1b.asm"
	include "r4/gfx_lists_1b.asm"
	include "r4/data_1b.asm"

; ------------------------------------------------------------------------------
