; ------------------------------------------------------------------------------

ObjectIndex:
	dc.l	PlayerObject
	dc.l	PlayerObject
	dc.l	PowerupObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	TestObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	SpringObject
	dc.l	HDoorSplashObject
	dc.l	HDoorSplashSetObject
	dc.l	HDoorObject
	dc.l	TunnelSplashObject
	dc.l	MoveSpringObject
	dc.l	RingObject
	dc.l	LostRingObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	BigRingObject
	dc.l	CapsuleObject
	dc.l	GoalObject
	dc.l	SignpostObject
	dc.l	ExplosionObject
	dc.l	MonitorTimeObject
	dc.l	MonitorItemObject
	dc.l	BoulderObject
	dc.l	HudPointsObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	FlowerObject
	dc.l	NullObject
	dc.l	PlatformObject
	dc.l	TamabbohObject
	dc.l	UnusedMissileObject
	dc.l	AnimalObject
	dc.l	NullObject
	dc.l	SpikesObject
	dc.l	NullObject
	dc.l	SpringboardObject
	dc.l	NullObject
	dc.l	EggmanObject
	dc.l	BossBodyObject
	dc.l	BossThighObject
	dc.l	BossCalfObject
	dc.l	BossFootObject
	dc.l	BossElbowObject
	dc.l	BossUpperArmObject
	dc.l	BossForearmObject
	dc.l	BossBumperObject
	dc.l	NullObject
	dc.l	RollTunnelObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	ResultsObject
	dc.l	GameOverObject
	dc.l	TitleCardObject
	dc.l	MosquiObject
	dc.l	PataBataObject
	dc.l	AntonObject
	dc.l	TagaTagaObject

; ------------------------------------------------------------------------------