; ------------------------------------------------------------------------------

ObjectIndex:
	dc.l	PlayerObject
	dc.l	PlayerObject
	dc.l	PowerupObject
	dc.l	WaterfallObject
	dc.l	EarthquakeObject
	dc.l	TestObject
	dc.l	TunnelPathObject
	dc.l	EarthquakeSetObject
	dc.l	SpinDiscObject
	dc.l	SpringObject
	dc.l	HDoorSplashObject
	dc.l	HDoorSplashSetObject
	dc.l	HDoorObject
	dc.l	TunnelSplashObject
	dc.l	MobileSpringObject
	dc.l	RingObject
	dc.l	LostRingObject
	dc.l	FloatBlockObject
	dc.l	CheckpointObject
	dc.l	BigRingObject
	dc.l	CapsuleObject
	dc.l	GoalObject
	dc.l	SignpostObject
	dc.l	ExplosionObject
	dc.l	MonitorTimeObject
	dc.l	MonitorItemObject
	dc.l	BoulderObject
	dc.l	HudPointsObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	FlowerObject
	dc.l	CollapseFloorObject
	dc.l	PlatformObject
	dc.l	TamabbohObject
	dc.l	UnusedMissileObject
	dc.l	AnimalObject
	dc.l	NullObject
	dc.l	SpikesObject
	dc.l	NullObject
	dc.l	SpringboardObject
	dc.l	NullObject
	dc.l	Booster3dObject
	dc.l	NullObject
	dc.l	Plant3dObject
	dc.l	RobotGeneratorObject
	dc.l	ProjectorObject
	dc.l	AmyRoseObject
	dc.l	HeartObject
	dc.l	PlayerHoleObject
	dc.l	NullObject
	dc.l	LogShadowObject
	dc.l	RollTunnelObject
	dc.l	VDoorObject
	dc.l	BreakWallObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	ResultsObject
	dc.l	GameOverObject
	dc.l	TitleCardObject
	dc.l	MosquiObject
	dc.l	PataBataObject
	dc.l	AntonObject
	dc.l	TagaTagaObject

; ------------------------------------------------------------------------------