; ------------------------------------------------------------------------------

ObjectIndex:
	dc.l	PlayerObject
	dc.l	PlayerObject
	dc.l	PowerupObject
	dc.l	WaterSurfaceObject
	dc.l	BreakPoleObject
	dc.l	TestObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	SpringObject
	dc.l	SplashObject
	dc.l	SplashObject
	dc.l	SplashObject
	dc.l	SplashObject
	dc.l	MoveSpringObject
	dc.l	RingObject
	dc.l	LostRingObject
	dc.l	NullObject
	dc.l	CheckpointObject
	dc.l	BigRingObject
	dc.l	CapsuleObject
	dc.l	GoalObject
	dc.l	SignpostObject
	dc.l	ExplosionObject
	dc.l	MonitorTimeObject
	dc.l	MonitorItemObject
	dc.l	BoulderObject
	dc.l	HudPointsObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	FlowerObject
	dc.l	BubbleSpawnerObject
	dc.l	PlayerBubblesObject
	dc.l	SpikesObject
	dc.l	NullObject
	dc.l	HMoveBlockObject
	dc.l	BigDoorObject
	dc.l	ElevatorObject
	dc.l	SwitchObject
	dc.l	DoorObject
	dc.l	SwingObject
	dc.l	NullObject
	dc.l	TonboObject
	dc.l	AmenboObject
	dc.l	TagaTagaObject
	dc.l	YagoObject
	dc.l	AnimalObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	CrushBlocksObject
	dc.l	BlockObject
	dc.l	FanObject
	dc.l	MaceObject
	dc.l	SpikeBallObject
	dc.l	NullObject
	dc.l	CollapseFloorObject
	dc.l	ResultsObject
	dc.l	GameOverObject
	dc.l	TitleCardObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	ShooterObject
	dc.l	NullObject
	dc.l	WoodBlockObject
	dc.l	MoveWallObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	NullObject
	dc.l	BreakBlockObject
	dc.l	RobotGeneratorObject
	dc.l	NullObject

; ------------------------------------------------------------------------------