; -------------------------------------------------------------------------
; Sonic CD Disassembly
; -------------------------------------------------------------------------
; Collision Chaos Act 1 Present
; -------------------------------------------------------------------------

	include	"Level/_Definitions.inc"

; -------------------------------------------------------------------------

	include	"Level/Initialization.asm"
	include	"Level/Collision Chaos/Palette Cycle (Present).asm"
	include	"Level/Palette Fade.asm"
	include	"Level/Palette Load (Fade).asm"
	include	"Level/Palette Load.asm"
	include	"Level/Collision Chaos/Palette Data (Act 1 Present).asm"
	include	"Level/Functions (Misc).asm"
	include	"Level/Collision Floor.asm"
	include	"Level/Main.asm"
	include	"Level/Functions (General).asm"
	include	"Level/Collision Chaos/Stage Draw (Act 1 Present).asm"
	include	"Level/Block Draw.asm"
	include	"Level/Collision Chaos/Scroll (Act 1 Present).asm"
	include	"Level/Palmtree Panic/Load Level Data.asm"
	include	"Level/_Events.asm"
	include	"Level/Object Functions.asm"
	include	"Level/Collision Chaos/Object Index (Act 1 Present).asm"
	include	"Level/_Objects/Sonic/Main.asm"
	include	"Level/Palmtree Panic/Player Special Collision.asm"
	include	"Level/Sub CPU.asm"
	include	"Level/Object Animate.asm"
	include	"Level/_Objects/Checkpoint/Main.asm"
	include	"Level/Resume Music (Leftover).asm"
	include	"Level/_Objects/Test Badnik/Main.asm"
	include	"Level/_Objects/Explosion/Main.asm"
	include	"Level/_Objects/Flower/Main.asm"
	include	"Level/_Objects/Spin Tunnel/Main (Waterfall Splash).asm"
	include	"Level/_Objects/Spin Tunnel/Main (Door).asm"
	include	"Level/_Objects/Powerup/Main.asm"
	include	"Level/_Objects/Spin Tunnel/Main (Tag).asm"
	include	"Level/Load Saved Data.asm"
	include	"Level/Collision Check.asm"
	include	"Level/Wacky Workbench/Player Object Collision.asm"
	include	"Level/Debug Mode.asm"
	include	"Level/Collision Chaos/Debug Objects (Act 1 Present).asm"
	include	"Level/Object Spawner.asm"
	include	"Level/Collision Chaos/Object Layout (Act 1).asm"
	include	"Level/Object Solid.asm"
	include	"Level/Collision Chaos/Objects/Bumper and Flipper/Main.asm"
	include	"Level/Collision Chaos/Objects/Block/Main.asm"
	include	"Level/Collision Chaos/Objects/Metal Platform/Main.asm"
	include	"Level/Collision Chaos/Objects/KamaKama/Main.asm"
	include	"Level/Collision Chaos/Objects/Fire Shooter/Main.asm"
	include	"Level/Collision Chaos/Objects/Drum Platform/Main.asm"
	include	"Level/Collision Chaos/Objects/Spike Chain/Main.asm"
	include	"Level/Collision Chaos/Objects/Glass Shatter/Main.asm"
	include	"Level/Collision Chaos/Objects/Bumper Platform/Main.asm"
	include	"Level/Collision Chaos/Objects/Teleporter/Main.asm"
	include	"Level/Collision Chaos/Objects/Door/Main.asm"
	include	"Level/_Objects/Boulder/Main.asm"
	include	"Level/_Objects/Spring/Main.asm"
	include	"Level/_Objects/Ring/Main.asm"
	include	"Level/_Objects/Floating Block/Main.asm"
	include	"Level/_Objects/Monitor and Time Post/Main.asm"
	include	"Level/_Objects/HUD and Points/Main.asm"
	include	"Level/_Objects/Spikes/Main.asm"
	include	"Level/_Objects/Level End/Main.asm"
	include	"Level/_Objects/Game Over/Main.asm"
	include	"Level/_Objects/Title Card/Main.asm"
	include	"Level/_Objects/Results/Main.asm"
	include	"Level/Palmtree Panic/Title Card Data.asm"
	include	"Level/Section Art Load.asm"
	include	"Level/Collision Chaos/Section Data (Act 1 Present).asm"
	include	"Level/Object Tile ID Set.asm"
	include	"Level/Collision Chaos/Object Tile IDs (Act 1 Present).asm"
	include	"Level/_Objects/Robot Generator/Main.asm"
	include	"Level/Palmtree Panic/Objects/Projector/Main.asm"
	include	"Level/Object Time Check.asm"
	include	"Level/Collision Chaos/Animated Tiles Update (Act 1 Present).asm"
	include	"Level/Collision Chaos/Objects/Robot Generator/Tile IDs.asm"
	include	"Level/Collision Chaos/Objects/Ga/Main.asm"
	include	"Level/Collision Chaos/Objects/Tentou/Main.asm"
	include	"Level/Collision Chaos/Objects/Pocket/Main.asm"
	include	"Level/Collision Chaos/Objects/Intro Spikes/Main.asm"
	include	"Level/Collision Chaos/Objects/Metal Sonic/Main.asm"
	include	"Level/Collision Chaos/Objects/Amy Rose/Main.asm"
	include	"Level/Collision Chaos/Data (Act 1 Present).asm"

; -------------------------------------------------------------------------
